// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgXXDts6mdq-sieV2itQhpyOaE3Tdlk44',
    appId: '1:1029843653320:web:5b47973a34436a4652cbfd',
    messagingSenderId: '1029843653320',
    projectId: 'foodcal-41824',
    authDomain: 'foodcal-41824.firebaseapp.com',
    storageBucket: 'foodcal-41824.firebasestorage.app',
    measurementId: 'G-4955D2DC6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDPVFUZCPh2t4DKHbR-fQlGa4HQsNAXfg',
    appId: '1:1029843653320:android:5eddacf16b8d536752cbfd',
    messagingSenderId: '1029843653320',
    projectId: 'foodcal-41824',
    storageBucket: 'foodcal-41824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-V9OodU9fwXizuddJompjz_gypFef00',
    appId: '1:1029843653320:ios:8fd5133455e0a74b52cbfd',
    messagingSenderId: '1029843653320',
    projectId: 'foodcal-41824',
    storageBucket: 'foodcal-41824.firebasestorage.app',
    iosBundleId: 'com.example.hoseo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW-V9OodU9fwXizuddJompjz_gypFef00',
    appId: '1:1029843653320:ios:8fd5133455e0a74b52cbfd',
    messagingSenderId: '1029843653320',
    projectId: 'foodcal-41824',
    storageBucket: 'foodcal-41824.firebasestorage.app',
    iosBundleId: 'com.example.hoseo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgXXDts6mdq-sieV2itQhpyOaE3Tdlk44',
    appId: '1:1029843653320:web:c96eadc9312db19052cbfd',
    messagingSenderId: '1029843653320',
    projectId: 'foodcal-41824',
    authDomain: 'foodcal-41824.firebaseapp.com',
    storageBucket: 'foodcal-41824.firebasestorage.app',
    measurementId: 'G-KZRTVWN2YK',
  );
}
